spring:
  application:
    name: yudao-server

  profiles:
    active: local

  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。

  # Servlet 配置
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # 解决 SpringFox 与 SpringBoot 2.6.x 不兼容的问题，参见 SpringFoxHandlerProviderBeanPostProcessor 类
#    throw-exception-if-no-handler-found: true # 404 错误时抛出异常，方便统一处理
#    static-path-pattern: /static/** # 静态资源路径; 注意：如果不配置，则 throw-exception-if-no-handler-found 不生效！！！ TODO 芋艿：不能配置，会导致 swagger 不生效

  # Jackson 配置项
  jackson:
    serialization:
      write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false # 允许序列化无属性的 Bean

  # Cache 配置项
  cache:
    type: REDIS
    redis:
      time-to-live: 1h # 设置过期时间为 1 小时

knife4j:
  enable: true
  setting:
    language: zh_cn

# MyBatis Plus 的配置项
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      id-type: NONE # “智能”模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
#      id-type: AUTO # 自增 ID，适合 MySQL 等直接自增的数据库
#      id-type: INPUT # 用户输入 ID，适合 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库
#      id-type: ASSIGN_ID # 分配 ID，默认使用雪花算法。注意，Oracle、PostgreSQL、Kingbase、DB2、H2 数据库时，需要去除实体类上的 @KeySequence 注解
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false # 关闭控制台的 Banner 打印
  type-aliases-package: ${yudao.info.base-package}.module.*.dal.dataobject # 指定扫描的包，多个包用逗号分隔
  encryptor:
    password: XDV71a+xqStEA3WH # 加解密的秘钥，可使用 https://www.imaegoo.com/2020/aes-key-generator/ 网站生成

mybatis-plus-join:
  banner: false # 关闭控制台的 Banner 打印

yudao:
  security:
    enable: true # 是否开启安全模块
    ignore-urls: # 忽略安全校验的 URL 列表
      - /admin-api/system/captcha/get # 获取图片验证码
      - /admin-api/system/captcha/check # 校验图片验证码
      - /admin-api/system/tenant/get-id-by-name # 基于名字获取租户
      - /admin-api/system/tenant/get-by-website # 基于域名获取租户
      - /admin-api/system/sms/callback/* # 短信回调接口
      - /admin-api/pay/notify/** # 支付回调通知
      - /jmreport/* # 积木报表
      - /ureport/* # UReport 报表
      - /app-api/*
      - /admin-api/mp/open/** # 微信公众号开放平台，微信回调接口
      - /admin-api/system/oss/callback/** # OSS 回调接口
      - /admin-api/system/oss/download/** # OSS 下载接口
      - /admin-api/system/oss/upload/** # OSS 上传接口
      - /admin-api/system/oss/upload-base64/** # OSS 上传接口
      - /admin-api/system/oss/upload-url/** # OSS 上传接口
      - /admin-api/system/oss/upload-multipart/** # OSS 上传接口
      - /admin-api/system/oss/upload-multipart-base64/** # OSS 上传接口
      - /admin-api/system/oss/upload-multipart-url/** # OSS 上传接口
      - /admin-api/system/oss/upload-multipart-file/** # OSS 上传接口
      - /admin-api/system/oss/upload-multipart-files/** # OSS 上传接口
      - /admin-api/system/oss/upload-multipart-file-base64/** # OSS 上传接口
      - /admin-api/system/oss/upload-multipart-file-url/** # OSS 上传接口
      - /admin-api/system/oss/upload-multipart-file-file/** # OSS 上传接口
      - /admin-api/system/oss/upload-multipart-file-files/** # OSS 上传接口
      - /admin-api/system/oss/upload-multipart-files-base64/** # OSS 上传
  codegen:
    enable: true # 是否开启代码生成器
    frontType: 30 # 前端类型，vue 或者 react
    dbSchemas: # 数据库 Schema 列表
      - ordinals
    basePackage: cn.iocoder.yudao # 项目的基础包名
  sms-code:
    expireTimes: 300 # 短信验证码的过期时间，单位：秒
    sendFrequency: 10 # 短信验证码的最大发送次数
    beginCode: 100000 # 短信验证码的起始值
    endCode: 999999 # 短信验证码的结束值
    sendMaximumQuantityPerDay: 100 # 每天发送短信的最大数量
  websocket:
    enable: true
    sender-type: redis # 消息发送方式，redis 或者 local
    path: /websocket
    max-text-message-buffer-size: 8192
    max-binary-message-buffer-size: 8192
    max-session-idle-timeout: 1800000
    max-frame-size: 8192
    async-send-timeout: 10000
    max-sessions: 1000
    max-text-message-size: 8192
    max-binary-message-size: 8192
    max-session-queue-size: 1000
    max-session-queue-size-reject: 1000
    max-session-queue-size-reject-message: "WebSocket session queue is full, max session queue size is 1000"
    max-session-queue-size-reject-code: 4008
    max-session-queue-size-reject-http-status: 400
    max-session-queue-size-reject-http-body: "WebSocket session queue is full, max session queue size is 1000"
    max-session-queue-size-reject-http-content-type: "text/plain;charset=UTF-8"
    max-session-queue-size-reject-http-headers:
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, OPTIONS"
      Access-Control-Allow-Headers: "Content-Type, x-requested-with, X-Custom-Header, HaiYi-Access-Token"
      Access-Control-Allow-Credentials: "true"
      Access-Control-Max-Age: "3600"
  info:
    version: 1.0.0
    base-package: cn.iocoder.yudao
  error-code: # 错误码相关配置项
    constants-class-list:
      - cn.iocoder.yudao.module.bpm.enums.ErrorCodeConstants
      - cn.iocoder.yudao.module.infra.enums.ErrorCodeConstants
      - cn.iocoder.yudao.module.member.enums.ErrorCodeConstants
      - cn.iocoder.yudao.module.pay.enums.ErrorCodeConstants
      - cn.iocoder.yudao.module.system.enums.ErrorCodeConstants
      - cn.iocoder.yudao.module.mp.enums.ErrorCodeConstants
  tenant: # 多租户相关配置项
    enable: true
    ignore-urls:
      - /admin-api/system/tenant/get-id-by-name # 基于名字获取租户，不许带租户编号
      - /admin-api/system/tenant/get-by-website # 基于域名获取租户，不许带租户编号
      - /admin-api/system/captcha/get # 获取图片验证码，和租户无关
      - /admin-api/system/captcha/check # 校验图片验证码，和租户无关
      - /admin-api/infra/file/*/get/** # 获取图片，和租户无关
      - /admin-api/system/sms/callback/* # 短信回调接口，无法带上租户编号
      - /admin-api/pay/notify/** # 支付回调通知，不携带租户编号
      - /jmreport/* # 积木报表，无法携带租户编号
      - /ureport/* # UReport 报表，无法携带租户编号
      - /admin-api/mp/open/** # 微信公众号开放平台，微信回调接口，无法携带租户编号
    ignore-tables:
      - system_tenant
      - system_tenant_package
      - system_dict_data
      - system_dict_type
      - system_error_code
      - system_menu
      - system_sms_channel
      - system_sms_template
      - system_sms_log
      - system_sensitive_word
      - system_oauth2_client
      - system_mail_account
      - system_mail_template
      - system_mail_log
      - system_notify_template
      - infra_codegen_column
      - infra_codegen_table
      - infra_test_demo
      - infra_config
      - infra_file_config
      - infra_file
      - infra_file_content
      - infra_job
      - infra_job_log
      - infra_job_log
      - infra_data_source_config
      - jimu_dict
      - jimu_dict_item
      - jimu_report
      - jimu_report_data_source
      - jimu_report_db
      - jimu_report_db_field
      - jimu_report_db_param
      - jimu_report_link
      - jimu_report_map
      - jimu_report_share
      - report_ureport_data
      - rep_demo_dxtj
      - rep_demo_employee
      - rep_demo_gongsi
      - rep_demo_jianpiao
      - tmp_report_data_1
      - tmp_report_data_income
debug: false

